### ISSUE TITLE
ValueError: [MAIXPY]kpu: load error:2002, ERR_KMODEL_VERSION: only support kmodel V3/V4 now

### ISSUE THREAD

**Issue by CatchZeng** [sipeed/train_scripts#14]
使用 <https://github.com/sipeed/maix_train> 在 linux 下训练 <https://github.com/sipeed/maix_train/blob/master/datasets/test_classifier_datasets.zip>，并拷贝到板子上运行，出现如下错误：

`ValueError: [MAIXPY]kpu: load error:2002, ERR_KMODEL_VERSION: only support kmodel V3/V4 now`。

![](https://user-images.githubusercontent.com/10027281/140687238-1c644579-1aff-497b-8cda-15328a189dee.jpeg)

使用的是最新的固件 <https://dl.sipeed.com/shareURL/MAIX/MaixPy/release/master/maixpy_v0.6.2_72_g22a8555b5>

**Comment by CatchZeng** [comment]
通过 <https://www.maixhub.com/ModelTraining> 训练后导出的与本地 linux 训练导出的 out 怎么内容不一样啊。 比如：`README.txt`

<img width="684" alt="截屏2021-11-08 下午1 07 58" src="https://user-images.githubusercontent.com/10027281/140687496-73cf0c72-ce1f-407a-9763-89894c8a6fb4.png">


<img width="589" alt="截屏2021-11-08 下午1 08 06" src="https://user-images.githubusercontent.com/10027281/140687510-990aacb8-19e3-4299-b7a8-52635945d91b.png">

是不是本仓库你们还没更新到与  <https://www.maixhub.com/ModelTraining>  一致啊？

**Comment by Neutree** [comment]
没有烧录模型到板子吧

**Comment by CatchZeng** [comment]
> 没有烧录模型到板子吧

感谢解答，刚才找出问题了，小伙伴把固件搞错了，没有烧录带 ide 的固件。

但是，那个本地和 <https://www.maixhub.com/ModelTraining> 得到的结果（out） 不一致是怎么回事啊？

**Comment by Neutree** [comment]
代码不一样吧  这个代码和maixhub不是完全一样的
