### ISSUE TITLE
Can I retrain the trained model?

### ISSUE THREAD

**Issue by sahinemreaslan** [sipeed/train_scripts#17]
I want to retrain using pretrained model. my project is based on object detection. 

maix_train/train/detector/weights/ "mobilenet_7_5_224_tf_no_top.h5"  Is it enough to replace it with the previous m_best.h5 model?

I actually want to do transfer learning thanks in advance

**Comment by kissablemt** [comment]
@voidstring 
this is the solution
https://github.com/sipeed/maix_train/issues/21

**Comment by sahinemreaslan** [comment]
@kissablemt Thank you
